apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xsqlinstances.aws.platform.upbound.io
spec:
  claimNames:
    kind: SQLInstance
    plural: sqlinstances
  connectionSecretKeys:
    - username
    - password
    - endpoint
    - host
  group: aws.platform.upbound.io
  names:
    kind: XSQLInstance
    plural: xsqlinstances
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  properties:
                    region:
                      type: string
                      description: Region is the region you'd like your resource to be created in.
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    engine:
                      type: string
                      description: This RDS Instance engine, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                      enum:
                        - postgres
                        - mariadb
                    engineVersion:
                      type: string
                      description: This RDS Instance engine version, see https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html for possible values.
                    storageGB:
                      type: integer
                    passwordSecretRef:
                      type: object
                      description: "A reference to the Secret object containing database password"
                      properties:
                        namespace:
                          type: string
                        name:
                          type: string
                        key:
                          type: string
                      required:
                        - namespace
                        - name
                        - key
                    autoGeneratePassword:
                      type: boolean
                    networkRef:
                      type: object
                      description: "A reference to the Network object that this database should be connected to."
                      properties:
                        id:
                          type: string
                          description: ID of the Network object this ref points to.
                      required:
                        - id
                  required:
                    - region
                    - engine
                    - engineVersion
                    - storageGB
                    - networkRef
                    - passwordSecretRef
              required:
                - parameters
            status:
              type: object
              properties:
                performanceMetrics:
                  type: object
                  description: Performance metrics from CloudWatch for this RDS instance
                  x-kubernetes-preserve-unknown-fields: true
                claudeDecision:
                  type: object
                  description: AI-driven scaling decision analysis from Claude
                  properties:
                    reasoning:
                      type: string
                      description: Detailed reasoning for the scaling decision
                    timestamp:
                      type: string
                      format: date-time
                      description: When the decision was made
                  required:
                  - reasoning
                  - timestamp
