name: End to End Testing

on:
  # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
  # pull_request_target is potentially dangerous target so we keep it strict
  # under the label and benefit from secret propagation
  pull_request_target:
    types:
      - synchronize
      - labeled

env:
  UP_API_TOKEN: ${{ secrets.UP_E2E_API_TOKEN || secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_E2E_ORG || secrets.UP_ORG }}
  UP_GROUP: ${{ secrets.UP_E2E_GROUP || secrets.UP_GROUP || 'default' }}
  UP_ROBOT_ID: ${{ secrets.UP_E2E_ROBOT_ID || secrets.UP_ROBOT_ID }}

jobs:
  e2e:
    if: contains(github.event.pull_request.labels.*.name, 'run-e2e-tests')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Build project
        run: up project build

      - name: Run e2e tests
        run: up test run tests/* --e2e --local
